homepage: "https://github.com/tangodelta217/nema-connectome-artix7"
main_repo: "https://github.com/tangodelta217/nema-connectome-artix7"
language: python
primary_contact: "mariano.millananco@gmail.com"
