"""Command implementations for the scaffolded NEMA CLI."""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

from .fixed import run_selftest as run_fixed_selftest
from .ir import IRValidationError, validate_ir


def write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def check_ir(ir_path: Path) -> tuple[int, dict]:
    try:
        report = validate_ir(ir_path)
    except FileNotFoundError:
        return 1, {"ok": False, "error": f"file not found: {ir_path}"}
    except IRValidationError as exc:
        return 1, {"ok": False, "error": str(exc)}
    return 0, report


def run_sim(ir_path: Path, ticks: int, out_path: Path) -> tuple[int, dict]:
    code, report = check_ir(ir_path)
    if code != 0:
        return code, report
    if ticks < 0:
        return 1, {"ok": False, "error": "--ticks must be >= 0"}

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as stream:
        for tick in range(ticks):
            line = {
                "tick": tick,
                "kind": "placeholder_tick",
                "ir_sha256": report["ir_sha256"],
                "note": "golden semantics not implemented yet",
            }
            stream.write(json.dumps(line, sort_keys=True) + "\n")

    return 0, {
        "ok": True,
        "trace_path": str(out_path),
        "ticks": ticks,
        "ir_sha256": report["ir_sha256"],
        "mode": "placeholder",
    }


def run_compile(ir_path: Path, outdir: Path) -> tuple[int, dict]:
    code, report = check_ir(ir_path)
    if code != 0:
        return code, report

    outdir.mkdir(parents=True, exist_ok=True)
    kernel_cpp = outdir / "kernel.cpp"
    kernel_cpp.write_text(
        """#include <ap_int.h>

// Placeholder kernel generated by `nema compile`.
extern "C" void nema_kernel(const ap_int<16>* in, ap_int<16>* out, int n) {
#pragma HLS INTERFACE m_axi port=in offset=slave bundle=gmem0
#pragma HLS INTERFACE m_axi port=out offset=slave bundle=gmem1
#pragma HLS INTERFACE s_axilite port=in bundle=control
#pragma HLS INTERFACE s_axilite port=out bundle=control
#pragma HLS INTERFACE s_axilite port=n bundle=control
#pragma HLS INTERFACE s_axilite port=return bundle=control

    for (int i = 0; i < n; ++i) {
#pragma HLS PIPELINE II=1
        out[i] = in[i];
    }
}
""",
        encoding="utf-8",
    )

    manifest = {
        "ok": True,
        "mode": "placeholder",
        "generator": "nema compile",
        "ir_sha256": report["ir_sha256"],
        "artifacts": {
            "kernel_cpp": str(kernel_cpp),
        },
    }
    manifest_path = outdir / "compile_manifest.json"
    write_json(manifest_path, manifest)

    return 0, {
        "ok": True,
        "outdir": str(outdir),
        "kernel_cpp": str(kernel_cpp),
        "manifest": str(manifest_path),
        "ir_sha256": report["ir_sha256"],
        "mode": "placeholder",
    }


def _detect_vitis_hls() -> dict:
    binary = shutil.which("vitis_hls")
    if not binary:
        return {
            "vitis_hls_found": False,
            "binary": None,
            "status": "unavailable",
            "detail": "vitis_hls not found on PATH",
        }

    proc = subprocess.run([binary, "-version"], check=False, capture_output=True, text=True)
    first_line = (proc.stdout or proc.stderr).splitlines()
    version_line = first_line[0] if first_line else "unknown"
    return {
        "vitis_hls_found": True,
        "binary": binary,
        "status": "available_not_invoked",
        "detail": "cosim flow scaffolded but not implemented yet",
        "version_line": version_line,
        "exit_code": proc.returncode,
    }


def run_hwtest(ir_path: Path, outdir: Path, ticks: int) -> tuple[int, dict]:
    outdir.mkdir(parents=True, exist_ok=True)

    sim_code, sim_report = run_sim(ir_path, ticks=ticks, out_path=outdir / "trace.jsonl")
    if sim_code != 0:
        return sim_code, sim_report

    compile_code, compile_report = run_compile(ir_path, outdir=outdir)
    if compile_code != 0:
        return compile_code, compile_report

    cosim_report = _detect_vitis_hls()
    bench_report = {
        "ok": True,
        "mode": "placeholder",
        "ir_path": str(ir_path),
        "ir_sha256": sim_report["ir_sha256"],
        "ticks": ticks,
        "sim": sim_report,
        "compile": compile_report,
        "cosim": cosim_report,
        "result": "stub_complete",
    }

    bench_report_path = outdir / "bench_report.json"
    write_json(bench_report_path, bench_report)
    return 0, {
        "ok": True,
        "bench_report": str(bench_report_path),
        "mode": "placeholder",
    }


def selftest_fixed() -> tuple[int, dict]:
    report = run_fixed_selftest()
    return (0 if report["ok"] else 1), report
